version: '3.8'
services:
  boilerplate:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - fcaramez
  test-boilerplate:
    image: postgres:15
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - fcaramez
networks:
  fcaramez:
